/**
 * Regenerates the bundled protobuf descriptor from the vendored .proto files.
 * Usage: npm run proto:gen   (or: node scripts/gen-proto.mjs)
 *
 * Emits lib/mammotion/protocol/generated/descriptor.ts — a plain TS module that
 * embeds the protobufjs JSON descriptor, so no JSON-import or filesystem access is
 * needed at runtime (important for the Homey sandbox).
 *
 * pbjs is run via npx (protobufjs-cli pins protobufjs@8 as a peer, which conflicts
 * with our runtime protobufjs@7 — so it is NOT a saved devDependency; the JSON
 * descriptor format is stable across major versions).
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const protoDir = join(root, 'lib/mammotion/protocol/proto');
const outTs = join(root, 'lib/mammotion/protocol/generated/descriptor.ts');

const json = execFileSync(
  'npx',
  ['-y', '-p', 'protobufjs-cli', 'pbjs', '-t', 'json', 'luba_msg.proto'],
  { cwd: protoDir, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 },
);

const parsed = JSON.parse(json); // validate

// Strip the `protoName` field annotations emitted by newer pbjs — they are not part
// of protobufjs@7's INamespace type (tsc rejects them) and are unused at runtime.
function stripProtoName(node) {
  if (Array.isArray(node)) {
    node.forEach(stripProtoName);
  } else if (node && typeof node === 'object') {
    delete node.protoName;
    Object.values(node).forEach(stripProtoName);
  }
}
stripProtoName(parsed);

const header =
  '// AUTO-GENERATED by scripts/gen-proto.mjs from lib/mammotion/protocol/proto/*.proto — do not edit.\n' +
  '// Regenerate with: npm run proto:gen\n\n' +
  "import type { INamespace } from 'protobufjs';\n\n" +
  'export const protoDescriptor: INamespace = ';
writeFileSync(outTs, `${header}${JSON.stringify(parsed)};\n`);
console.log('Wrote', outTs, `(${(JSON.stringify(parsed).length / 1024).toFixed(0)} KB)`);
